name: Clone emortal package from immortalwrt/openwrt-23.05

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Run every day at midnight UTC

jobs:
  clone-emortal-package:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Initialize Git repository
      run: |
        git init
        git remote add origin https://github.com/immortalwrt/immortalwrt.git

    - name: Fetch openwrt-23.05 branch
      run: git fetch --depth=1 origin openwrt-23.05

    - name: Clone emortal package from immortalwrt
      run: |
        git checkout -b openwrt-23.05 origin/openwrt-23.05
        mkdir -p emortal
        cp -R emortal_temp/package/emortal/* emortal

    - name: Commit and push changes
      run: |
        git add emortal
        git commit -m "Update emortal package from immortalwrt/openwrt-23.05"
        git push origin main
